#~ ======================================================================
#~ Gabriele Filomena - 09.02.2023
#~ ======================================================================
#~ conda install mkdocs mkdocs-material pymdown-extensions
#~ pip install mkdocs-bibtex
#~ mkdocs new .
#~
#~ mkdocs serve
#~ ======================================================================
site_name: The cityImage user manual
site_author: Gabriele Filomena
site_url: https://cityImage.readthedocs.io/en/latest

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - python

plugins:
  - search

markdown_extensions:
  - footnotes
  - pymdownx.emoji:
  - attr_list #~ [label](url){target=_blank}

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Nodes and Paths - from OpenStreetMap': '01-Nodes_Paths_fromOSM.md'
        - 'Nodes and Paths - from Local Files': '02-Nodes_Paths_Local_Files.md'
        - 'Regions (Districts)': '03-District identification.md'
        - 'Barriers (Edges)': '04-Barriers_fromOSM.md'
        - 'Landmarks': '05-Landmarks.md'

    - About:
        - 'About': 'about.md'

